# fly.toml app configuration file generated for pingriverlevels on 2024-11-01T14:21:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pingriverlevels'
primary_region = 'sin'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/mnt/data/data.db'
  PHX_HOST = 'pingriverlevels.fly.dev'
  PORT = '8080'

[[mounts]]
  source = 'data'
  destination = '/mnt/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
